// Rusti's historical customer base spans these 8 countries; the rest cover
// other likely shipping destinations for a worldwide online store.
export const COUNTRIES = [
  "Philippines",
  "Australia",
  "Japan",
  "Germany",
  "United States",
  "Singapore",
  "South Korea",
  "New Zealand",
  "Canada",
  "United Kingdom",
  "Ireland",
  "France",
  "Netherlands",
  "Italy",
  "Spain",
  "Sweden",
  "Switzerland",
  "Hong Kong",
  "Taiwan",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "India",
  "United Arab Emirates",
  "Other",
];
